import 'package:flutter/material.dart';

/// The three lifecycle states a dragon fruit tree icon can be drawn in.
/// Empty/Flowering are derived from the stored flower count; Fruiting is
/// only ever shown in Fruit View and never persisted (see
/// FruitCalculationService).
enum TreeState { empty, flowering, fruiting }

extension TreeStateX on TreeState {
  String get assetPath {
    switch (this) {
      case TreeState.empty:
        return 'assets/icons/tree_empty.png';
      case TreeState.flowering:
        return 'assets/icons/tree_flowering.png';
      case TreeState.fruiting:
        return 'assets/icons/tree_fruiting.png';
    }
  }
}

/// Which season view a counting session is being browsed in. Flower View
/// always shows the raw recorded data; Fruit View is only offered once a
/// session is 40+ days old (see FruitCalculationService.isFruitViewUnlocked)
/// and shows a dynamically estimated fruit count that is never stored.
enum SeasonView { flower, fruit }

/// One-tap date-range presets for the Analytics Map filter bar. Each maps
/// to a concrete (mode, startDate) pair resolved in AnalyticsProvider.
enum QuickFilter { today, yesterday, last7Days, last30Days, thisMonth, thisSeason, customRange, untilToday }

extension QuickFilterX on QuickFilter {
  String get label {
    switch (this) {
      case QuickFilter.today:
        return 'Today';
      case QuickFilter.yesterday:
        return 'Yesterday';
      case QuickFilter.last7Days:
        return 'Last 7 Days';
      case QuickFilter.last30Days:
        return 'Last 30 Days';
      case QuickFilter.thisMonth:
        return 'This Month';
      case QuickFilter.thisSeason:
        return 'This Season';
      case QuickFilter.customRange:
        return 'Custom Range';
      case QuickFilter.untilToday:
        return 'Until Today';
    }
  }
}

/// The three dragon fruit varieties tracked by post color.
enum PostColor { yellow, red, white }

extension PostColorX on PostColor {
  String get label {
    switch (this) {
      case PostColor.yellow:
        return 'Yellow';
      case PostColor.red:
        return 'Red';
      case PostColor.white:
        return 'White';
    }
  }

  /// Stored representation in SQLite (keep stable — used as a DB value).
  String get dbValue => name;

  static PostColor fromDb(String value) {
    return PostColor.values.firstWhere(
      (c) => c.dbValue == value,
      orElse: () => PostColor.yellow,
    );
  }

  /// High-contrast colors chosen for outdoor / bright-sunlight readability.
  Color get swatch {
    switch (this) {
      case PostColor.yellow:
        return const Color(0xFFF5B301);
      case PostColor.red:
        return const Color(0xFFD32F2F);
      case PostColor.white:
        return const Color(0xFFECEFF1);
    }
  }

  Color get onSwatch {
    switch (this) {
      case PostColor.white:
        return const Color(0xFF2B2B2B);
      default:
        return Colors.white;
    }
  }
}

/// Editor tool modes for the farm layout canvas. `select` is Multi-Select:
/// tap trees or drag a rectangle to build a working group, then act on all
/// of them at once via the group action bar (Move/Color/Duplicate/Delete).
enum EditorTool { addPost, move, delete, duplicate, addRow, select }

/// Which phase of the free-form Field Boundary workflow the editor is in.
/// `none` = normal layout editing; `creating` = tapping points to build a
/// new boundary; `editing` = an existing boundary's vertices are shown and
/// (depending on [BoundaryEditTool]) draggable, insertable, or deletable.
enum BoundaryMode { none, creating, editing }

/// Sub-tool active while BoundaryMode.editing. Only one is active at a
/// time, mirroring EditorTool's single-active-tool pattern.
enum BoundaryEditTool { move, addPoint, deletePoint }

/// How the farm layout is being rendered right now.
/// 2D is the default, editable, fast-counting map (unchanged FarmCanvas).
/// 3D is a read-only isometric presentation view for visualization only —
/// never used for counting or editing.
enum ViewMode { twoD, threeD }

class AppConstants {
  AppConstants._();

  static const String appName = 'DragonTrack';

  // Canvas / editor
  static const double postIconSize = 44.0;
  static const double gridSize = 40.0;

  /// Spacing between trees generated by "Add Tree Row", in world units.
  /// Deliberately 2 grid cells, not 1: a single grid cell (gridSize = 40.0)
  /// is smaller than a tree icon itself (postIconSize = 44.0), so a row
  /// spaced exactly one grid cell apart had trees visually overlapping.
  /// This stays tied to the same grid system (still a clean multiple of
  /// gridSize, so it snaps consistently) — just far enough apart that each
  /// tree reads as a distinct, tappable object.
  static const double rowTreeSpacing = gridSize * 2;
  static const double minCanvasScale = 0.25;
  static const double maxCanvasScale = 4.0;

  // Performance: farms may contain up to this many posts without lag.
  static const int maxSupportedPosts = 3000;
}
